const actions = {
  UPDATE_LOAN: 'UPDATE_LOAN',
  UPDATE_WITH_INSURANCE: 'UPDATE_WITH_INSURANCE',
  UPDATE_MONTHS: 'UPDATE_MONTHS',
  CALC_LOAN_SEND: 'CALC_LOAN_SEND',
  UPDATE_SUMMARY_FIELDS: 'UPDATE_SUMMARY_FIELDS'
}

module.exports = actions
